package com.allen.sales.infrastructure.persistence.mapper;

import com.allen.sales.domain.model.Sale;
import com.allen.sales.domain.model.SaleItem;
import com.allen.sales.infrastructure.persistence.entity.SaleEntity;
import com.allen.sales.infrastructure.persistence.entity.SaleItemEntity;
import org.mapstruct.AfterMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring")
public interface SaleMapper {

    // ==== SalesOrder ====

    @Mapping(target = "items", source = "items")
    SaleEntity toEntity(Sale domain);

    @InheritInverseConfiguration
    Sale toDomain(SaleEntity entity);

    // ==== SalesOrderItem ====

    // id is generated by DB, salesOrder is set in @AfterMapping
    @Mapping(target = "idSaleItem", ignore = true)
    @Mapping(target = "sale", ignore = true)
    SaleItemEntity toEntity(SaleItem domain);

    @InheritInverseConfiguration
    SaleItem toDomain(SaleItemEntity entity);

    // Set back-reference from item entities to their parent order entity
    @AfterMapping
    default void setBackReference(@MappingTarget SaleEntity saleEntity) {
        if (saleEntity.getItems() != null) {
            saleEntity.getItems().forEach(item -> item.setSale(saleEntity));
        }
    }
}